### ISSUE TITLE
BBL

### ISSUE THREAD

**Issue by emamer** [CityOfNewYork/nyc-geo-metadata#4]
Can you add BBL back into this dataset?

**Comment by ekamptner** [comment]
Hi enamer, 

Which dataset are you referring to? This github page has metadata for several datasets.

**Comment by juanfrans** [comment]
Hi, I think @emamer is referring to the building footprint dataset. It used to have the BBL number but doesn't anymore. It only has the BIN and the DOITT_ID numbers as identifiers.

It would be great if you could add it back.

Thanks!

**Comment by ekamptner** [comment]
Hi all,

The BBLs were dropped from the building footprints dataset because tax lot information is constantly changing and often becomes out of sync with our buildings footprint dataset. If you need BBL information with the building dataset, I would recommend creating a spatial join with DCP's Map Pluto datasets. This will give you the most up to date BBL information for each building. 

Map Pluto -- https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-pluto-mappluto.page

Erika

**Comment by emamer** [comment]
Hi Erika,

Understood. That’s what I ended up doing. Thanks!

Best,

Liz Mamer

Sightline Coordinator

[TitleVest Agency, LLC.]<https://www.titlevest.com/>

110 East 42nd Street, 10th Floor

New York, NY 10017

D

646.429.3004

T

212-757-5800


E

emamer@titlevest.com<mailto:emamer@titlevest.com>

W

www.titlevest.com<https://www.titlevest.com/>
